language: python
services:
- postgresql
addons:
  postgresql: "9.5"
python:
- 3.6
install:
- pip install -r requirements/local.txt
before_script:
- psql -c 'create database miseq_portal;' -U postgres
script:
- python manage.py makemigrations core
- python manage.py makemigrations users
- python manage.py makemigrations analysis
- python manage.py makemigrations miseq_viewer
- python manage.py migrate --fake-initial
- pytest
